apiVersion: v1
kind: Service
metadata:
  name: price-service-node-port
spec:
  type: NodePort
  ports:
    - port: 5050
      targetPort: 5001
      nodePort: 30555
  selector:
    component: price-service-deployment